In [392]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

airq_data = pd.read_csv('world_air_quality.csv', delimiter=';') #read data and organize into columns using delimiter
airq_data

,Country Code,City,Location,Coordinates,Pollutant,Source Name,Unit,Value,Last Updated,Country Label
0,JP,NaN,北九州市小倉北区大門一丁目６－４８,"33.880833, 130.873056",NO,japan-soramame,ppm,0.002,2024-03-10T13:30:00+05:30,Japan
1,JP,NaN,北九州市若松区本町三丁目１３－１,"33.898056, 130.81",NO2,japan-soramame,ppm,0.005,2024-03-10T13:30:00+05:30,Japan
2,JP,NaN,北九州市門司区大里原町１２－１２,"33.895833, 130.935833",NOX,japan-soramame,ppm,0.013,2024-03-10T13:30:00+05:30,Japan
3,JP,NaN,千歳市若草４－１３,"42.786944, 141.605",NO2,japan-soramame,ppm,0.004,2024-03-10T13:30:00+05:30,Japan
4,JP,NaN,千葉市稲毛区宮野木町９９６－９,"35.653889, 140.097778",NOX,japan-soramame,ppm,0.003,2024-03-10T13:30:00+05:30,Japan
...,...,...,...,...,...,...,...,...,...,...
54250,IT,MONITORING NETWORK OF REGIONE BASILICATA,NET.IT133A,"40.64389299999999, 15.872893000000001",CO,EEA Italy,µg/m³,295.000,2024-03-11T15:30:00+05:30,Italy
54251,IT,RETE REGIONALE QUALITA' ARIA DEL VENETO,NET.IT281A,"46.030833, 11.905833",O3,EEA Italy,µg/m³,35.000,2024-03-11T15:30:00+05:30,Italy
54252,IT,RETE REGIONALE QUALITA' DELL'ARIA DELLA TOSCANA,NET.IT279A,"43.55472, 10.32972",CO,EEA Italy,µg/m³,600.000,2024-03-11T15:30:00+05:30,Italy
54253,IT,RETE REGIONALE QUALITA' DELL'ARIA DELLA TOSCANA,NET.IT279A,"43.91611, 11.006939999999998",PM2.5,EEA Italy,µg/m³,15.000,2024-03-11T04:30:00+05:30,Italy
54254,IT,RETE REGIONALE QUALITA' DELL'ARIA DELLA TOSCANA,NET.IT279A,"43.91611, 11.006939999999998",O3,EEA Italy,µg/m³,30.000,2024-03-11T15:30:00+05:30,Italy

In [393]:
#remove spaces from left and right of strings
airq_data.columns = airq_data.columns.str.lstrip()
airq_data.columns = airq_data.columns.str.rstrip()
airq_data

,Country Code,City,Location,Coordinates,Pollutant,Source Name,Unit,Value,Last Updated,Country Label
0,JP,NaN,北九州市小倉北区大門一丁目６－４８,"33.880833, 130.873056",NO,japan-soramame,ppm,0.002,2024-03-10T13:30:00+05:30,Japan
1,JP,NaN,北九州市若松区本町三丁目１３－１,"33.898056, 130.81",NO2,japan-soramame,ppm,0.005,2024-03-10T13:30:00+05:30,Japan
2,JP,NaN,北九州市門司区大里原町１２－１２,"33.895833, 130.935833",NOX,japan-soramame,ppm,0.013,2024-03-10T13:30:00+05:30,Japan
3,JP,NaN,千歳市若草４－１３,"42.786944, 141.605",NO2,japan-soramame,ppm,0.004,2024-03-10T13:30:00+05:30,Japan
4,JP,NaN,千葉市稲毛区宮野木町９９６－９,"35.653889, 140.097778",NOX,japan-soramame,ppm,0.003,2024-03-10T13:30:00+05:30,Japan
...,...,...,...,...,...,...,...,...,...,...
54250,IT,MONITORING NETWORK OF REGIONE BASILICATA,NET.IT133A,"40.64389299999999, 15.872893000000001",CO,EEA Italy,µg/m³,295.000,2024-03-11T15:30:00+05:30,Italy
54251,IT,RETE REGIONALE QUALITA' ARIA DEL VENETO,NET.IT281A,"46.030833, 11.905833",O3,EEA Italy,µg/m³,35.000,2024-03-11T15:30:00+05:30,Italy
54252,IT,RETE REGIONALE QUALITA' DELL'ARIA DELLA TOSCANA,NET.IT279A,"43.55472, 10.32972",CO,EEA Italy,µg/m³,600.000,2024-03-11T15:30:00+05:30,Italy
54253,IT,RETE REGIONALE QUALITA' DELL'ARIA DELLA TOSCANA,NET.IT279A,"43.91611, 11.006939999999998",PM2.5,EEA Italy,µg/m³,15.000,2024-03-11T04:30:00+05:30,Italy
54254,IT,RETE REGIONALE QUALITA' DELL'ARIA DELLA TOSCANA,NET.IT279A,"43.91611, 11.006939999999998",O3,EEA Italy,µg/m³,30.000,2024-03-11T15:30:00+05:30,Italy

In [394]:
# drop unnecessary columns
airq_data = airq_data.drop(['Country Code','City','Location','Coordinates','Source Name', 'Last Updated'],axis=1)
airq_data

      Pollutant   Unit    Value Country Label
0            NO    ppm    0.002         Japan
1           NO2    ppm    0.005         Japan
2           NOX    ppm    0.013         Japan
3           NO2    ppm    0.004         Japan
4           NOX    ppm    0.003         Japan
...         ...    ...      ...           ...
54250        CO  µg/m³  295.000         Italy
54251        O3  µg/m³   35.000         Italy
54252        CO  µg/m³  600.000         Italy
54253     PM2.5  µg/m³   15.000         Italy
54254        O3  µg/m³   30.000         Italy

[54255 rows x 4 columns]

In [395]:
#rename "Country Label" to 'Country'
airq_data.rename(columns={'Country Label': 'Country'}, inplace=True)
airq_data

      Pollutant   Unit    Value Country
0            NO    ppm    0.002   Japan
1           NO2    ppm    0.005   Japan
2           NOX    ppm    0.013   Japan
3           NO2    ppm    0.004   Japan
4           NOX    ppm    0.003   Japan
...         ...    ...      ...     ...
54250        CO  µg/m³  295.000   Italy
54251        O3  µg/m³   35.000   Italy
54252        CO  µg/m³  600.000   Italy
54253     PM2.5  µg/m³   15.000   Italy
54254        O3  µg/m³   30.000   Italy

[54255 rows x 4 columns]

In [396]:
# Drop rows with NaN values in 'Country', 'Pollutant', or 'Value' columns
airq_data.dropna(subset=['Country', 'Pollutant', 'Value'], inplace=True)

print(airq_data)

      Pollutant   Unit    Value Country
0            NO    ppm    0.002   Japan
1           NO2    ppm    0.005   Japan
2           NOX    ppm    0.013   Japan
3           NO2    ppm    0.004   Japan
4           NOX    ppm    0.003   Japan
...         ...    ...      ...     ...
54250        CO  µg/m³  295.000   Italy
54251        O3  µg/m³   35.000   Italy
54252        CO  µg/m³  600.000   Italy
54253     PM2.5  µg/m³   15.000   Italy
54254        O3  µg/m³   30.000   Italy

[54140 rows x 4 columns]

In [397]:
# Update the DataFrame to keep only rows where the "Unit" is either "ppm" or "ug/cm^3"
airq_data = airq_data[(airq_data['Unit'] == 'ppm') | (airq_data['Unit'] == 'µg/m³')]
#airq_data

# Drop rows with negative values in the 'Value' column
airq_data = airq_data[airq_data['Value'] >= 0]

airq_data

      Pollutant   Unit    Value Country
0            NO    ppm    0.002   Japan
1           NO2    ppm    0.005   Japan
2           NOX    ppm    0.013   Japan
3           NO2    ppm    0.004   Japan
4           NOX    ppm    0.003   Japan
...         ...    ...      ...     ...
54250        CO  µg/m³  295.000   Italy
54251        O3  µg/m³   35.000   Italy
54252        CO  µg/m³  600.000   Italy
54253     PM2.5  µg/m³   15.000   Italy
54254        O3  µg/m³   30.000   Italy

[53348 rows x 4 columns]

In [398]:
# Convert all data into one unit for uniformity

# Molecular weights of gases (in g/mol)
molecular_weights = {
    'CO': 28.01,     # Carbon Monoxide
    'NO': 30.01,     # Nitric Oxide
    'NO2': 46.01,    # Nitrogen Dioxide
    'NOX': 46.01,    # Nitrogen Oxides (Sum of NO and NO2)
    'O3': 48.00,     # Ozone
    'PM2.5': 12.01,  # Particulate Matter ≤ 2.5 µm
    'SO2': 64.07     # Sulfur Dioxide
}

# Identify pollutants measured in ppm and convert their values to µg/m³
for index, row in airq_data.iterrows():
    pollutant = row['Pollutant']
    if pollutant in molecular_weights and row['Unit'] == 'ppm':
        molecular_weight = molecular_weights[pollutant]
        # Convert ppm to µg/m³ using the conversion factor: 1 ppm = 1 µg/m³ (assuming 1 m³ volume)
        conversion_factor = molecular_weight * 1e6
        airq_data.at[index, 'Value'] *= conversion_factor

# Drop the 'Unit' column
airq_data = airq_data.drop(['Unit'],axis=1)

airq_data

      Pollutant     Value Country
0            NO   60020.0   Japan
1           NO2  230050.0   Japan
2           NOX  598130.0   Japan
3           NO2  184040.0   Japan
4           NOX  138030.0   Japan
...         ...       ...     ...
54250        CO     295.0   Italy
54251        O3      35.0   Italy
54252        CO     600.0   Italy
54253     PM2.5      15.0   Italy
54254        O3      30.0   Italy

[53348 rows x 3 columns]

In [399]:
# Data Discretization

# Quartiles for the 'Value' column
Q1 = airq_data['Value'].quantile(0.25)
Q3 = airq_data['Value'].quantile(0.75)

# quartile boundaries
quarts = [0.0, Q1, Q3, float('inf')]

# Labels for quartile categories
labels = ['Low', 'Medium', 'High']

# New column 'Pollution Category' based on quartile categories
airq_data['Pollution Category'] = pd.cut(airq_data['Value'], bins=quarts, labels=labels, include_lowest=True)

# Drop the 'Value' column
airq_data = airq_data.drop(['Value'],axis=1)

airq_data

      Pollutant Country Pollution Category
0            NO   Japan               High
1           NO2   Japan               High
2           NOX   Japan               High
3           NO2   Japan               High
4           NOX   Japan               High
...         ...     ...                ...
54250        CO   Italy             Medium
54251        O3   Italy             Medium
54252        CO   Italy               High
54253     PM2.5   Italy             Medium
54254        O3   Italy             Medium

[53348 rows x 3 columns]

In [410]:
from sklearn.preprocessing import OneHotEncoder

# categorical columns for one-hot encoding
categorical_cols = ['Country', 'Pollutant', 'Pollution Category']

encoder = OneHotEncoder(sparse_output=False)
# sparse_output=False ensures the output is a dense array

# Fit and transform
onehot_encoded_data = encoder.fit_transform(airq_data[categorical_cols])

# Converting the encoded data into a DataFrame with proper column names
encoded_df = pd.DataFrame(onehot_encoded_data, columns=encoder.get_feature_names_out(categorical_cols))

# encoded data with headings
print(encoded_df)

       Country_Afghanistan  Country_Algeria  Country_Andorra  \
0                      0.0              0.0              0.0
1                      0.0              0.0              0.0
2                      0.0              0.0              0.0
3                      0.0              0.0              0.0
4                      0.0              0.0              0.0
...                    ...              ...              ...
53343                  0.0              0.0              0.0
53344                  0.0              0.0              0.0
53345                  0.0              0.0              0.0
53346                  0.0              0.0              0.0
53347                  0.0              0.0              0.0

       Country_Antigua and Barbuda  Country_Argentina  Country_Armenia  \
0                              0.0                0.0              0.0
1                              0.0                0.0              0.0
2                              0.0                0.0              0.0
3                              0.0                0.0              0.0
4                              0.0                0.0              0.0
...                            ...                ...              ...
53343                          0.0                0.0              0.0
53344                          0.0                0.0              0.0
53345                          0.0                0.0              0.0
53346                          0.0                0.0              0.0
53347                          0.0                0.0              0.0

       Country_Australia  Country_Austria  Country_Azerbaijan  \
0                    0.0              0.0                 0.0
1                    0.0              0.0                 0.0
2                    0.0              0.0                 0.0
3                    0.0              0.0                 0.0
4                    0.0              0.0                 0.0
...                  ...              ...                 ...
53343                0.0              0.0                 0.0
53344                0.0              0.0                 0.0
53345                0.0              0.0                 0.0
53346                0.0              0.0                 0.0
53347                0.0              0.0                 0.0

       Country_Bahrain  ...  Pollutant_NO2  Pollutant_NOX  Pollutant_O3  \
0                  0.0  ...            0.0            0.0           0.0
1                  0.0  ...            1.0            0.0           0.0
2                  0.0  ...            0.0            1.0           0.0
3                  0.0  ...            1.0            0.0           0.0
4                  0.0  ...            0.0            1.0           0.0
...                ...  ...            ...            ...           ...
53343              0.0  ...            0.0            0.0           0.0
53344              0.0  ...            0.0            0.0           1.0
53345              0.0  ...            0.0            0.0           0.0
53346              0.0  ...            0.0            0.0           0.0
53347              0.0  ...            0.0            0.0           1.0

       Pollutant_PM1  Pollutant_PM10  Pollutant_PM2.5  Pollutant_SO2  \
0                0.0             0.0              0.0            0.0
1                0.0             0.0              0.0            0.0
2                0.0             0.0              0.0            0.0
3                0.0             0.0              0.0            0.0
4                0.0             0.0              0.0            0.0
...              ...             ...              ...            ...
53343            0.0             0.0              0.0            0.0
53344            0.0             0.0              0.0            0.0
53345            0.0             0.0              0.0            0.0
53346            0.0             0.0              1.0            0.0
53347            0.0             0.0              0.0            0.0

       Pollution Category_High  Pollution Category_Low  \
0                          1.0                     0.0
1                          1.0                     0.0
2                          1.0                     0.0
3                          1.0                     0.0
4                          1.0                     0.0
...                        ...                     ...
53343                      0.0                     0.0
53344                      0.0                     0.0
53345                      1.0                     0.0
53346                      0.0                     0.0
53347                      0.0                     0.0

       Pollution Category_Medium
0                            0.0
1                            0.0
2                            0.0
3                            0.0
4                            0.0
...                          ...
53343                        1.0
53344                        1.0
53345                        0.0
53346                        1.0
53347                        1.0

[53348 rows x 124 columns]

In [416]:
# frequent itemsets using Apriori algorithm
frequent_itemsets1 = apriori(encoded_df, min_support=0.1, use_colnames=True)

print(frequent_itemsets1)

C:\Users\Zain\AppData\Local\Programs\Python\Python312\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:109: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

     support                                      itemsets
0   0.208311                               (Country_China)
1   0.117511                               (Country_Japan)
2   0.110651                       (Country_United States)
3   0.184431                               (Pollutant_NO2)
4   0.155601                                (Pollutant_O3)
5   0.149771                              (Pollutant_PM10)
6   0.175545                             (Pollutant_PM2.5)
7   0.127015                               (Pollutant_SO2)
8   0.247938                     (Pollution Category_High)
9   0.250262                      (Pollution Category_Low)
10  0.501800                   (Pollution Category_Medium)
11  0.150877    (Pollution Category_Medium, Country_China)
12  0.131683   (Pollution Category_Medium, Pollutant_PM10)
13  0.107408  (Pollutant_PM2.5, Pollution Category_Medium)

In [417]:
# association rules
rules1 = association_rules(frequent_itemsets1, metric="confidence", min_threshold=0.6)

print("Association Rules:")
print(rules1)

Association Rules:
         antecedents                  consequents  antecedent support  \
0    (Country_China)  (Pollution Category_Medium)            0.208311
1   (Pollutant_PM10)  (Pollution Category_Medium)            0.149771
2  (Pollutant_PM2.5)  (Pollution Category_Medium)            0.175545

   consequent support   support  confidence      lift  leverage  conviction  \
0              0.5018  0.150877    0.724287  1.443379  0.046347    1.806952
1              0.5018  0.131683    0.879224  1.752142  0.056527    4.124997
2              0.5018  0.107408    0.611853  1.219317  0.019319    1.283534

   zhangs_metric
0       0.388008
1       0.504888
2       0.218167

In [430]:
# frequent itemsets using Apriori algorithm
frequent_itemsets2 = apriori(encoded_df, min_support=0.05, use_colnames=True)

# Sort frequent itemsets by support in descending order
sorted_frequent_itemsets2 = frequent_itemsets2.sort_values(by='support', ascending=False)

# Print the sorted frequent itemsets
print(sorted_frequent_itemsets2)


# association rules
rules2 = association_rules(frequent_itemsets2, metric="confidence", min_threshold=0.7)

print("Association Rules:")
print(rules2)

C:\Users\Zain\AppData\Local\Programs\Python\Python312\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:109: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

     support                                          itemsets
13  0.501800                       (Pollution Category_Medium)
12  0.250262                          (Pollution Category_Low)
11  0.247938                         (Pollution Category_High)
0   0.208311                                   (Country_China)
6   0.184431                                   (Pollutant_NO2)
9   0.175545                                 (Pollutant_PM2.5)
7   0.155601                                    (Pollutant_O3)
14  0.150877        (Pollution Category_Medium, Country_China)
8   0.149771                                  (Pollutant_PM10)
22  0.131683       (Pollution Category_Medium, Pollutant_PM10)
10  0.127015                                   (Pollutant_SO2)
1   0.117511                                   (Country_Japan)
3   0.110651                           (Country_United States)
24  0.107408      (Pollutant_PM2.5, Pollution Category_Medium)
19  0.097829        (Pollution Category_Medium, Pollutant_NO2)
21  0.095336         (Pollution Category_Medium, Pollutant_O3)
4   0.094455                                    (Pollutant_CO)
15  0.078016          (Country_Japan, Pollution Category_High)
25  0.072524           (Pollution Category_Low, Pollutant_SO2)
5   0.070706                                    (Pollutant_NO)
23  0.067894         (Pollutant_PM2.5, Pollution Category_Low)
2   0.060827                                   (Country_Spain)
17  0.058409           (Pollutant_CO, Pollution Category_High)
16  0.055841  (Country_United States, Pollution Category_High)
20  0.052017           (Pollution Category_High, Pollutant_O3)
18  0.050911          (Pollution Category_High, Pollutant_NO2)
Association Rules:
        antecedents                  consequents  antecedent support  \
0   (Country_China)  (Pollution Category_Medium)            0.208311
1  (Pollutant_PM10)  (Pollution Category_Medium)            0.149771

   consequent support   support  confidence      lift  leverage  conviction  \
0              0.5018  0.150877    0.724287  1.443379  0.046347    1.806952
1              0.5018  0.131683    0.879224  1.752142  0.056527    4.124997

   zhangs_metric
0       0.388008
1       0.504888

In [433]:
# frequent itemsets using Apriori algorithm
frequent_itemsets3 = apriori(encoded_df, min_support=0.025, use_colnames=True)

# Sort frequent itemsets by support in descending order
sorted_frequent_itemsets3 = frequent_itemsets3.sort_values(by='support', ascending=False)

# Print the sorted frequent itemsets
print(sorted_frequent_itemsets3)


# association rules
rules3 = association_rules(frequent_itemsets3, metric="confidence", min_threshold=0.8)

# Sort frequent itemsets by support in descending order
sorted_rules3 = rules3.sort_values(by='confidence', ascending=False)

print("Association Rules:")
print(sorted_rules3)

C:\Users\Zain\AppData\Local\Programs\Python\Python312\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:109: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

     support                                           itemsets
21  0.501800                        (Pollution Category_Medium)
20  0.250262                           (Pollution Category_Low)
19  0.247938                          (Pollution Category_High)
0   0.208311                                    (Country_China)
13  0.184431                                    (Pollutant_NO2)
..       ...                                                ...
36  0.026205                     (Pollutant_NOX, Country_Japan)
45  0.025943  (Country_United States, Pollution Category_Med...
65  0.025887  (Pollutant_NOX, Country_Japan, Pollution Categ...
64  0.025868  (Country_Japan, Pollution Category_High, Pollu...
6   0.025362                                   (Country_Mexico)

[67 rows x 2 columns]
Association Rules:
                             antecedents                  consequents  \
3          (Pollutant_O3, Country_China)  (Pollution Category_Medium)
8  (Country_United States, Pollutant_O3)    (Pollution Category_High)
7         (Pollutant_NOX, Country_Japan)    (Pollution Category_High)
6         (Country_Japan, Pollutant_NO2)    (Pollution Category_High)
4        (Pollutant_PM10, Country_China)  (Pollution Category_Medium)
0                        (Pollutant_NOX)    (Pollution Category_High)
1                       (Pollutant_PM10)  (Pollution Category_Medium)
5       (Pollutant_PM2.5, Country_China)  (Pollution Category_Medium)
2         (Country_China, Pollutant_NO2)  (Pollution Category_Medium)

   antecedent support  consequent support   support  confidence      lift  \
3            0.034753            0.501800  0.034640    0.996764  1.986379
8            0.032035            0.247938  0.031773    0.991808  4.000225
7            0.026205            0.247938  0.025887    0.987840  3.984220
6            0.026243            0.247938  0.025868    0.985714  3.975647
4            0.034697            0.501800  0.033666    0.970286  1.933614
0            0.037658            0.247938  0.034753    0.922847  3.722088
1            0.149771            0.501800  0.131683    0.879224  1.752142
5            0.034884            0.501800  0.030385    0.871037  1.735827
2            0.034697            0.501800  0.028323    0.816316  1.626776

   leverage  conviction  zhangs_metric
3  0.017201  153.943953       0.514450
8  0.023830   91.805275       0.774836
7  0.019389   61.846034       0.769166
6  0.019361   52.644335       0.768640
4  0.016255   16.766711       0.500188
0  0.025416    9.747693       0.759952
1  0.056527    4.124997       0.504888
5  0.012881    3.863130       0.439228
2  0.010913    2.712262       0.399136